<?php
/*
 *   Jamshidbek Akhlidinov
 *   12 - 1 2024 22:3:28
 *   https://ustadev.uz
 *   https://github.com/JamshidbekAkhlidinov
 */

namespace app\modules\admin\modules\landingElement\search;


use app\modules\admin\enums\LandingElementEnum;
use app\modules\admin\modules\landingElement\models\LandingElement;
use yii\data\ActiveDataProvider;

class ProcessSearch extends LandingElement
{
    public function rules()
    {
        return [
            [['title', 'description', 'order', 'files'], 'safe']
        ];
    }

    public function scenarios(): array
    {
        return parent::scenarios(); // TODO: Change the autogenerated stub
    }

    public function search($params): ActiveDataProvider
    {
        $query = LandingElement::find()
            ->andWhere([
                'key' => LandingElementEnum::PROCESS
            ]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            return $dataProvider;
        }

        $query->andFilterWhere(['order' => $this->order]);

        $query->andFilterWhere(['like', 'title', $this->title])
            ->andFilterWhere(['like', 'description', $this->description])
            ->andFilterWhere(['like', 'files', $this->files]);

        return $dataProvider;
    }
}